version: '3'
services:
  postgresql_db:
    restart: always
    container_name: drf_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - yatube_api_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - yatube_api_network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: destrifer@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: Centner1
        - yatube_api_network
  backend:
    restart: always
    container_name: drf_backend
    image: drf_yatube_backend
    build:
      context: .
      dockerfile: ../api_yamdb/Dockerfile
    volumes:
      - ./:/usr/src/drf
      - static_volume:/usr/src/drf/api_yamdb/staticfiles
    command: bash -c "cd /usr/src/drf/api_yamdb &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 --workers 3 api_yamdb.wsgi:application"
    depends_on:
      - postgresql_db
    networks:
      - yatube_api_network
    ports:
      - '8000:8000'
  nginx:
    restart: always
    container_name: nginx_drf
    image: nginx:latest
    depends_on:
      - backend
      - pgadmin
    networks:
      - yatube_api_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/drf/api_yamdb/staticfiles
    ports:
      - '80:80'
networks:
  yatube_api_network:

volumes:
  yatube_api_data:
  static_volume: